<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="3.0.2" />
    <PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageVersion Include="MSTest.TestAdapter" Version="2.2.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="2.2.3" />
    <PackageVersion Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>