<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<VersionPrefix>1.6.0</VersionPrefix>
	<Title>KotOR_IO</Title>
	<Description>Provides Input and Output functionality for common KotOR File Types</Description>
	<GenerateDocumentationFile>False</GenerateDocumentationFile>
	<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
	<Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\KotOR_IO.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>