<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>test8</AssemblyTitle>
    <Product>test8</Product>
    <Copyright>Copyright ©  2019</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KotOR_IO\KotOR_IO.csproj" />
  </ItemGroup>
</Project>